export default {
    post: null,
    duties: null,
    typeOfEmployment: null,
    schedule: null,
    salaryFrom: null,
    salaryBefore: null,
    qualificationRequirements: null,
    experience: null,
    education: null,
    workingConditions: null,
    vacancyVideo: null,
    officeAdress: null,
    houseNumber: null,
}